accountManager = false
namelockManager = true
newPlayerChooseVoc = false
newPlayerSpawnPosX = 1062
newPlayerSpawnPosY = 1894
newPlayerSpawnPosZ = 6
newPlayerTownId = 1
newPlayerLevel = 15
newPlayerMagicLevel = 0
generateAccountNumber = false
lightInterval = 7500
lightChange = 1
startupTime = 351
startupLight = 100
limitPokeballs = 6
happyDropTime = 12
minHappinessEffectDelay = 25
maxHappinessEffectDelay = 40
PokemonStageVeryHappy = 215
PokemonStageHappy = 160
PokemonStageOK = 110
PokemonStageSad = 50
PokemonStageMad = 0
maximumHunger = 120
stateHunger = 100
increaseHunger = 7
decreaseHappy = 1
decreaseHungryHappy = 4
useTeleportWithFly = false
dropHappyDuringBattles = true
allowBlockSpawn = false
rateGymSpellInterval = 0.68
redSkullLength = 30 * 24 * 60 * 60
blackSkullLength = 45 * 24 * 60 * 60
dailyFragsToRedSkull = 3
weeklyFragsToRedSkull = 5
monthlyFragsToRedSkull = 10
dailyFragsToBlackSkull = dailyFragsToRedSkull
weeklyFragsToBlackSkull = weeklyFragsToRedSkull
monthlyFragsToBlackSkull = monthlyFragsToRedSkull
dailyFragsToBanishment = dailyFragsToRedSkull
weeklyFragsToBanishment = weeklyFragsToRedSkull
monthlyFragsToBanishment = monthlyFragsToRedSkull
blackSkulledDeathHealth = 40
blackSkulledDeathMana = 0
useBlackSkull = false
useFragHandler = true
advancedFragList = false
notationsToBan = 3
warningsToFinalBan = 3
warningsToDeletion = 4
banLength = 7 * 24 * 60 * 60
killsBanLength = 7 * 24 * 60 * 60
finalBanLength = 30 * 24 * 60 * 60
ipBanishmentLength = 1 * 24 * 60 * 60
broadcastBanishments = true
maxViolationCommentSize = 200
violationNameReportActionType = 2
autoBanishUnknownBytes = true
worldType = "1"
protectionLevel = 1000
pvpTileIgnoreLevelAndVocationProtection = true
pzLocked = 18 * 1000
huntingDuration = 60 * 1000
criticalHitChance = 7
criticalHitMultiplier = 1
displayCriticalHitNotify = false
removeWeaponAmmunition = true
removeWeaponCharges = true
removeRuneCharges = true
whiteSkullTime = 15 * 60 * 1000
noDamageToSameLookfeet = false
showHealingDamage = false
showHealingDamageForMonsters = true
fieldOwnershipDuration = 5 * 1000
stopAttackingAtExit = false
oldConditionAccuracy = false
loginProtectionPeriod = 10 * 1000
deathLostPercent = 1
stairhopDelay = 0 * 1000
pushCreatureDelay = 1 * 1000
deathContainerId = 0
addonsOnlyPremium = false
max_packets_per_second = 1000
gainExperienceColor = 215
addManaSpentInPvPZone = true
squareColor = 0
allowFightback = true
worldId = 0
ip = "127.0.0.1"
gameVersion = "1.4" -- Thalles Vitor
bindOnlyConfiguredIpAddress = false
loginPort = 7183
gamePort = 7172
adminPort = 7183
statusPort = 7183
loginTries = 10
retryTimeout = 5 * 1000
loginTimeout = 60 * 1000
maxPlayers = 100
motd = "Bem-vindo ao mundo de Poke Night.\nWelcome to the world of Poke Night.\nBienvenido al mundo de Poke Night."
displayOnOrOffAtCharlist = false
onePlayerOnlinePerAccount = false
allowClones = false
serverName = "Green"
loginMessage = "Seja bem-vindo(a)."
statusTimeout = 5 * 60 * 1000
replaceKickOnLogin = true
forceSlowConnectionsToDisconnect = false
loginOnlyWithLoginServer = false
premiumPlayerSkipWaitList = true
sqlType = "mysql"
sqlHost = "localhost"
sqlPort = 7701
sqlUser = "root"
sqlPass = "251178"
sqlDatabase = "pokemysterious"
sqlFile = ""
sqlKeepAlive = 0
mysqlReadTimeout = 10
mysqlWriteTimeout = 10
encryptionType = "sha1"
deathListEnabled = true
deathListRequiredTime = 1 * 60 * 1000
deathAssistCount = 19
maxDeathRecords = 1
ingameGuildManagement = true
levelToFormGuild = 40
premiumDaysToFormGuild = 0
guildNameMinLength = 2
guildNameMaxLength = 25
highscoreDisplayPlayers = 15
updateHighscoresAfterMinutes = 60
buyableAndSellableHouses = true
houseNeedPremium = true
bedsRequirePremium = true
levelToBuyHouse = 100
housesPerAccount = 5
houseRentAsPrice = false
housePriceAsRent = false
housePriceEachSquare = 19275
houseRentPeriod = "never"
houseCleanOld = 0
guildHalls = false
timeBetweenActions = 500
timeBetweenExActions = 500
hotkeyAimbotEnabled = true
mapName = "PGalaxy"
mapAuthor = "Venez"
randomizeTiles = true
storeTrash = false
cleanProtectedZones = true
mailboxDisabledTowns = "1"
defaultPriority = "high"
niceLevel = 5
coresUsed = "-1"
optimizedatapackbaseAtStartup = true
removePremiumOnInit = true
confirmOutdatedVersion = false
formulaLevel = 5.0
formulaMagic = 1.0
bufferMutedOnSpellFailure = false
spellNameInsteadOfWords = false
emoteSpells = true
hideSpellWords = false
allowChangeOutfit = true
allowChangeColors = true
allowChangeAddons = true
disableOutfitsForPrivilegedPlayers = false
dataDirectory = "datapack/"
bankSystem = true
displaySkillLevelOnAdvance = false
promptExceptionTracerErrorBox = true
separateViplistPerCharacter = false
maximumDoorLevel = 500
maxMessageBuffer = 4
saveGlobalStorage = false
useHousedatapackStorage = false
storePlayerDirection = false
checkCorpseOwner = true
monsterLootMessage = 3
monsterLootMessageType = 25
ghostModeInvisibleEffect = true
ghostModeSpellEffects = true
idleWarningTime = 14 * 60 * 1000
idleKickTime = 15 * 60 * 1000
expireReportsAfterReads = 1
playerQueryDeepness = 2
maxItemsPerPZTile = 0
maxItemsPerHouseTile = 0
freePremium = false
premiumForPromotion = false
blessingOnlyPremium = true
blessingReductionBase = 30
blessingReductionDecreament = 5
eachBlessReduction = 8
experienceStages = true
rateExperience = 14
rateExperienceFromPlayers = 0
rateSkill = 1.0
rateMagic = 1.0
rateLoot = 10
rateSpawn = 2
rateMonsterHealth = 1.0
rateMonsterMana = 1.0
rateMonsterAttack = 3
rateMonsterDefense = 1.0
minLevelThresholdForKilledPlayer = 0.9
maxLevelThresholdForKilledPlayer = 1.1
rateStaminaLoss = 1
rateStaminaGain = 3
rateStaminaThresholdGain = 12
staminaRatingLimitTop = 41 * 60
staminaRatingLimitBottom = 14 * 60
rateStaminaAboveNormal = 1.0
rateStaminaUnderNormal = 1.0
staminaThresholdOnlyPremium = true
experienceShareRadiusX = 30
experienceShareRadiusY = 30
experienceShareRadiusZ = 1
experienceShareLevelDifference = 200 * 200
extraPartyExperienceLimit = 20
extraPartyExperiencePercent = 20
noDamageToGuildMates = false
noDamageToPartyMembers = true
experienceShareActivity = 2 * 60 * 1000
globalSaveEnabled = true
globalSaveHour = 12
shutdownAtGlobalSave = false
cleanMapAtGlobalSave = false
deSpawnRange = 2
deSpawnRadius = 25
maxPlayerSummons = 1
teleportAllSummons = true
teleportPlayerSummons = true
ownerName = "Venez"
ownerEmail = ""
url = ""
location = "Brazil"
displayGamemastersWithOnlineCommand = false
adminLogsEnabled = false
displayPlayersLogging = true
prefixChannelLogs = ""
runFile = ""
outLogName = ""
errorLogName = ""
truncateLogsOnStartup = false
accountSize = 5
attackSpeed = 30
capsystem = "no"